export const homeObjOne = {
  lightBg: false,
  imgStart:'',
  img:require('../../images/svg-1.svg').default,
  alt:'imgStart',
  start:'',
  lightTopLine:true,
  lightText:true,
  lightTextDesc:true,
  primary:true,
  buttonLabel:'Get Started',
  description:'We Help bunisess owner increase their revenur. Our team lorem',
  headLine:'Lead Generation aaaaaaaaaaaaaa',
  topLine:'Marketing agency',
};

export const homeObjTwo = {
    lightBg: true,
    imgStart:'start',
    img:require('../../images/profile.jpg'),
    alt:'imgStart',
    start:'true',
    lightTopLine:false,
    lightText:false,
    lightTextDesc:false,
    primary:false,
    buttonLabel:'Get Started',
    description:'We Help bunisess owner increase their revenur. Our team lorem',
    headLine:'Lead Generation aaaaaaaaaaaaaa',
    topLine:'Marketing agency',
  };

  export const homeObjTthree = {
    lightBg: false,
    imgStart:'',
    img:require('../../images/svg-2.svg').default,
    alt:'imgStart',
    start:'',
    lightTopLine:true,
    lightText:true,
    lightTextDesc:true,
    primary:true,
    buttonLabel:'Get Started',
    description:'We Help bunisess owner increase their revenur. Our team lorem',
    headLine:'Lead Generation aaaaaaaaaaaaaa',
    topLine:'Marketing agency',
  };
  export const homeObjFour = {
    lightBg: false,
    imgStart:'',
    img:require('../../images/svg-2.svg').default,
    alt:'imgStart',
    start:'',
    lightTopLine:true,
    lightText:true,
    lightTextDesc:true,
    primary:true,
    buttonLabel:'Get Started',
    description:'We Help bunisess owner increase their revenur. Our team lorem',
    headLine:'Lead Generation aaaaaaaaaaaaaa',
    topLine:'Marketing agency',
  };